In [1]:
pip install xlrd

  Obtaining dependency information for xlrd from https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/96.5 kB ? eta -:--:--
   ------------ --------------------------- 30.7/96.5 kB ? eta -:--:--
   -------------------------------------- - 92.2/96.5 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 96.5/96.5 kB 690.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [15]:
import pandas as pd
df = pd.read_excel(r"C:\Users\sakin\OneDrive\Masaüstü\OMÜ YL\Veri Bilimi\ÖDEV\kuzenler.xlsx")
print(df)

          İsim Cinsiyet  Yaş  Saat
0        Melih    Erkek   37     4
1        Kübra    Kadın   36     3
2        Büşra    Kadın   33     5
3       Kürşat    Erkek   28     2
4       Gülnur    Kadın   27     6
5        Feyzi    Erkek   25     1
6         Esra    Kadın   25     3
7        Zişan    Kadın   21     2
8      Mustafa    Erkek   19     4
9       Zeynep    Kadın   16     7
10  Hayrunnisa    Kadın   14     4


In [19]:
import pandas as pd
import numpy as np
df= {
    "İsim":["Melih","Kübra","Büşra","Kürşat","Gülnur","Feyzi","Esra","Zişan","Mustafa","Zeynep","Hayrunnisa"],
    "Cinsiyet":["Erkek","Kadın","Kadın","Erkek","Kadın","Erkek","Kadın","Kadın","Erkek","Kadın","Kadın"],
    "Yaş":[37,36,33,28,27,25,25,21,19,16,14], "Saat":[4,3,5,2,6,1,3,2,4,7,4]}
df=pd.DataFrame(df)
df

İsim Cinsiyet  Yaş  Saat
0        Melih    Erkek   37     4
1        Kübra    Kadın   36     3
2        Büşra    Kadın   33     5
3       Kürşat    Erkek   28     2
4       Gülnur    Kadın   27     6
5        Feyzi    Erkek   25     1
6         Esra    Kadın   25     3
7        Zişan    Kadın   21     2
8      Mustafa    Erkek   19     4
9       Zeynep    Kadın   16     7
10  Hayrunnisa    Kadın   14     4

In [21]:
df.mean() # veri çerçevesindeki verilerin ortalaması

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Yaş     25.545455
Saat     3.727273
dtype: float64

In [23]:
df.mean(axis=0) # sütun ortalamaları

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\2657802244.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df. mean(axis=0) # sütun ortalamaları


Yaş     25.545455
Saat     3.727273
dtype: float64

In [25]:
df.mean(axis=1) # satır ortalamaları (yaş ve saat ortalaması)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3676274908.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis=1)


0     20.5
1     19.5
2     19.0
3     15.0
4     16.5
5     13.0
6     14.0
7     11.5
8     11.5
9     11.5
10     9.0
dtype: float64

In [27]:
#SAAT DEĞİŞKENİNİN ORTALAMASI
df.loc[:,"Saat"].mean()

3.727272727272727

In [29]:
#Belirli bir sütunun ortalaması
df.loc[:,"Yaş"].mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0     37
1     36
2     33
3     28
4     27
5     25
6     25
7     21
8     19
9     16
10    14
Name: Yaş, dtype: int64>

In [31]:
#Geometrik Ortalama

In [35]:
#(3,11,9,5,6,6,17) sayılarının geometrik ortalamasını hesaplama
from scipy import stats
print(stats.gmean([3,11,9,5,6,6,17]))

7.099228013753606


In [41]:
#Veri çerçevesinin belirli sütunlarının geometrik ortalamasını hesaplama
import pandas as pd
import numpy as np
from scipy import stats
df = pd.read_excel(r"C:\Users\sakin\OneDrive\Masaüstü\OMÜ YL\Veri Bilimi\ÖDEV\kuzenler.xlsx")
print(df)
from scipy import stats
stats.gmean(df.iloc[:,2:4],axis=0)

          İsim Cinsiyet  Yaş  Saat
0        Melih    Erkek   37     4
1        Kübra    Kadın   36     3
2        Büşra    Kadın   33     5
3       Kürşat    Erkek   28     2
4       Gülnur    Kadın   27     6
5        Feyzi    Erkek   25     1
6         Esra    Kadın   25     3
7        Zişan    Kadın   21     2
8      Mustafa    Erkek   19     4
9       Zeynep    Kadın   16     7
10  Hayrunnisa    Kadın   14     4


array([24.43758374,  3.28693465])

In [45]:
stats.gmean(df.iloc[:,2:4],axis=1)

array([12.16552506, 10.39230485, 12.84523258,  7.48331477, 12.72792206,
        5.        ,  8.66025404,  6.4807407 ,  8.71779789, 10.58300524,
        7.48331477])

In [47]:
stats.gmean(df.loc[:,"Yaş"])

24.437583736406268

In [49]:
#Harmonik Ortalama

In [53]:
print(stats.hmean([4,11,15,16,5,7]))

7.380682952805698


In [55]:
from scipy import stats
stats.hmean(df.iloc[:,2:4],axis=0)

array([23.30319107,  2.801698  ])

In [61]:
stats.hmean(df.iloc[:,2:4],axis=1)

array([7.2195122 , 5.53846154, 8.68421053, 3.73333333, 9.81818182,
       1.92307692, 5.35714286, 3.65217391, 6.60869565, 9.73913043,
       6.22222222])

In [63]:
# Medyan

In [65]:
import pandas as pd
import numpy as np
df= {
    "İsim":["Melih","Kübra","Büşra","Kürşat","Gülnur","Feyzi","Esra","Zişan","Mustafa","Zeynep","Hayrunnisa"],
    "Cinsiyet":["Erkek","Kadın","Kadın","Erkek","Kadın","Erkek","Kadın","Kadın","Erkek","Kadın","Kadın"],
    "Yaş":[37,36,33,28,27,25,25,21,19,16,14], "Saat":[4,3,5,2,6,1,3,2,4,7,4]}
df=pd.DataFrame(df)
df
df.mean()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\2440493896.py:9: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Yaş     25.545455
Saat     3.727273
dtype: float64

In [67]:
df.median(axis=1)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3214761434.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median(axis=1)


0     20.5
1     19.5
2     19.0
3     15.0
4     16.5
5     13.0
6     14.0
7     11.5
8     11.5
9     11.5
10     9.0
dtype: float64

In [69]:
df.loc[:,"Saat"].median()

4.0

In [71]:
df.loc[:,"Yaş"].median()

25.0

In [ ]:
#Mod

In [77]:
df.mode()

İsim Cinsiyet   Yaş  Saat
0        Büşra    Kadın  25.0   4.0
1         Esra      NaN   NaN   NaN
2        Feyzi      NaN   NaN   NaN
3       Gülnur      NaN   NaN   NaN
4   Hayrunnisa      NaN   NaN   NaN
5        Kübra      NaN   NaN   NaN
6       Kürşat      NaN   NaN   NaN
7        Melih      NaN   NaN   NaN
8      Mustafa      NaN   NaN   NaN
9       Zeynep      NaN   NaN   NaN
10       Zişan      NaN   NaN   NaN

In [79]:
df.loc[:,"Yaş"].mode()

0    25
Name: Yaş, dtype: int64

In [81]:
df.loc[:,"Saat"].mode()

<bound method Series.mode of 0     4
1     3
2     5
3     2
4     6
5     1
6     3
7     2
8     4
9     7
10    4
Name: Saat, dtype: int64>

In [83]:
df.loc[:,"Cinsiyet"].mode()

0    Kadın
Name: Cinsiyet, dtype: object

In [85]:
# Kartiller

In [87]:
df.quantile()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\1407141079.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.quantile()


Yaş     25.0
Saat     4.0
Name: 0.5, dtype: float64

In [89]:
df.quantile(.25)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\493109538.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.quantile(.25)


Yaş     20.0
Saat     2.5
Name: 0.25, dtype: float64

In [91]:
df.quantile(.75)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3289849985.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.quantile(.75)


Yaş     30.5
Saat     4.5
Name: 0.75, dtype: float64

In [93]:
df.quantile(.1)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3430475897.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.quantile(.1)


Yaş     16.0
Saat     2.0
Name: 0.1, dtype: float64

In [95]:
df.quantile(.99)

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\4069167805.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.quantile(.99)


Yaş     36.9
Saat     6.9
Name: 0.99, dtype: float64

In [99]:
import numpy as np

In [101]:
np.ptp(df["Saat"])

6

In [103]:
np.ptp(df["Yaş"])

23

In [105]:
df.max()

İsim        Zişan
Cinsiyet    Kadın
Yaş            37
Saat            7
dtype: object

In [107]:
df.min()

<bound method NDFrame._add_numeric_operations.<locals>.min of           İsim Cinsiyet  Yaş  Saat
0        Melih    Erkek   37     4
1        Kübra    Kadın   36     3
2        Büşra    Kadın   33     5
3       Kürşat    Erkek   28     2
4       Gülnur    Kadın   27     6
5        Feyzi    Erkek   25     1
6         Esra    Kadın   25     3
7        Zişan    Kadın   21     2
8      Mustafa    Erkek   19     4
9       Zeynep    Kadın   16     7
10  Hayrunnisa    Kadın   14     4>

In [109]:
# YAŞA GÖRE MAX DEĞERE SAHİP SATIRI BULMA
df.loc[df["Yaş"].idxmax()]

İsim        Melih
Cinsiyet    Erkek
Yaş            37
Saat            4
Name: 0, dtype: object

In [115]:
# MAX YAŞA SAHİP ÜÇ SATIRI BULMA
df.nlargest(3,"Yaş")

İsim Cinsiyet  Yaş  Saat
0  Melih    Erkek   37     4
1  Kübra    Kadın   36     3
2  Büşra    Kadın   33     5

In [117]:
# Kartiller Arası Fark

In [119]:
from scipy.stats import iqr
iqr(df["Yaş"])

10.5

In [121]:
# Ortalama Sapma

In [123]:
df.mad()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3844944795.py:1: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  df.mad()


Yaş     6.049587
Saat    1.388430
dtype: float64

In [129]:
# Varyans Hesaplama

In [133]:
import numpy as np
print(np.var([11,91,5,6,81,71,34,9]))

1180.5


In [135]:
df.var()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\1568254755.py:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.var()


Yaş     59.272727
Saat     3.218182
dtype: float64

In [137]:
df.loc[:,"Saat"].var()

3.218181818181818

In [139]:
df.loc[:,"Yaş"].var()

59.27272727272727

In [141]:
# Standart SapmaHesaplama
import numpy as np
print(np.std([11,91,5,6,81,71,34,9]))

34.35840508521896


In [143]:
df.std()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\3390915376.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()


Yaş     7.698878
Saat    1.793929
dtype: float64

In [149]:
df.loc[:,"Yaş"].std()

7.6988783126327744

In [151]:
df.loc[:,"Saat"].std()

1.7939291563999449

In [153]:
# Standart Hata

In [155]:
df.sem()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\1459226325.py:1: FutureWarning: The default value of numeric_only in DataFrame.sem is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.sem()


Yaş     2.321299
Saat    0.540890
dtype: float64

In [157]:
# Çarpıklık

In [159]:
df.skew()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\1665899112.py:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.skew()


Yaş     0.078823
Saat    0.371624
dtype: float64

In [161]:
df.loc[:,"Yaş"].skew()

0.07882326374098676

In [163]:
df.loc[:,"Saat"].skew()

0.37162374238040335

In [165]:
# Basıklık

In [179]:
df.kurtosis()

C:\Users\sakin\AppData\Local\Temp\ipykernel_9716\615572439.py:1: FutureWarning: The default value of numeric_only in DataFrame.kurt is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.kurtosis()


Yaş    -1.003167
Saat   -0.312490
dtype: float64

In [183]:
df.loc[:,"Saat"].kurtosis()

-0.3124900252162526

In [181]:
df.loc[:,"Yaş"].kurtosis()

-1.0031667544883134

In [185]:
# Özet İstatiskler için

In [187]:
df.describe

<bound method NDFrame.describe of           İsim Cinsiyet  Yaş  Saat
0        Melih    Erkek   37     4
1        Kübra    Kadın   36     3
2        Büşra    Kadın   33     5
3       Kürşat    Erkek   28     2
4       Gülnur    Kadın   27     6
5        Feyzi    Erkek   25     1
6         Esra    Kadın   25     3
7        Zişan    Kadın   21     2
8      Mustafa    Erkek   19     4
9       Zeynep    Kadın   16     7
10  Hayrunnisa    Kadın   14     4>

In [191]:
# HERHANGİ BİR GRUBA GÖRE ÖZET İSTATİSTİKLER
df["Yaş"].groupby(df["Cinsiyet"]).describe()

count       mean      std   min   25%   50%    75%   max
Cinsiyet                                                          
Erkek       4.0  27.250000  7.50000  19.0  23.5  26.5  30.25  37.0
Kadın       7.0  24.571429  8.22308  14.0  18.5  25.0  30.00  36.0